version: '3'

tasks:
  run:
    cmds:
      - go run ./cmd/loxGo/main.go {{.CLI_ARGS}}

  genAst:
    cmds:
      - go run ./cmd/generateAst/main.go .

  fmt:
    cmds:
      - go fmt

  git:
    cmds:
      - git add .
      - git commit -m {{.CLI_ARGS}}
